/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedNovaRouteImport } from './routes/_authenticated/nova'
import { Route as AuthenticatedNeviraRouteImport } from './routes/_authenticated/nevira'
import { Route as ApiSpotifyCallbackRouteImport } from './routes/api/spotify/callback'
import { Route as AuthenticatedNovaThreadIdRouteImport } from './routes/_authenticated/nova.$threadId'
import { Route as AuthenticatedNeviraThreadIdRouteImport } from './routes/_authenticated/nevira.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNovaRoute = AuthenticatedNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNeviraRoute = AuthenticatedNeviraRouteImport.update({
  id: '/nevira',
  path: '/nevira',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSpotifyCallbackRoute = ApiSpotifyCallbackRouteImport.update({
  id: '/api/spotify/callback',
  path: '/api/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNovaThreadIdRoute =
  AuthenticatedNovaThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedNovaRoute,
  } as any)
const AuthenticatedNeviraThreadIdRoute =
  AuthenticatedNeviraThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedNeviraRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nevira': typeof AuthenticatedNeviraRouteWithChildren
  '/nova': typeof AuthenticatedNovaRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/nevira/$threadId': typeof AuthenticatedNeviraThreadIdRoute
  '/nova/$threadId': typeof AuthenticatedNovaThreadIdRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nevira': typeof AuthenticatedNeviraRouteWithChildren
  '/nova': typeof AuthenticatedNovaRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/nevira/$threadId': typeof AuthenticatedNeviraThreadIdRoute
  '/nova/$threadId': typeof AuthenticatedNovaThreadIdRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/nevira': typeof AuthenticatedNeviraRouteWithChildren
  '/_authenticated/nova': typeof AuthenticatedNovaRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/nevira/$threadId': typeof AuthenticatedNeviraThreadIdRoute
  '/_authenticated/nova/$threadId': typeof AuthenticatedNovaThreadIdRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nevira'
    | '/nova'
    | '/api/chat'
    | '/nevira/$threadId'
    | '/nova/$threadId'
    | '/api/spotify/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nevira'
    | '/nova'
    | '/api/chat'
    | '/nevira/$threadId'
    | '/nova/$threadId'
    | '/api/spotify/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/nevira'
    | '/_authenticated/nova'
    | '/api/chat'
    | '/_authenticated/nevira/$threadId'
    | '/_authenticated/nova/$threadId'
    | '/api/spotify/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSpotifyCallbackRoute: typeof ApiSpotifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nova': {
      id: '/_authenticated/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof AuthenticatedNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nevira': {
      id: '/_authenticated/nevira'
      path: '/nevira'
      fullPath: '/nevira'
      preLoaderRoute: typeof AuthenticatedNeviraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/spotify/callback': {
      id: '/api/spotify/callback'
      path: '/api/spotify/callback'
      fullPath: '/api/spotify/callback'
      preLoaderRoute: typeof ApiSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nova/$threadId': {
      id: '/_authenticated/nova/$threadId'
      path: '/$threadId'
      fullPath: '/nova/$threadId'
      preLoaderRoute: typeof AuthenticatedNovaThreadIdRouteImport
      parentRoute: typeof AuthenticatedNovaRoute
    }
    '/_authenticated/nevira/$threadId': {
      id: '/_authenticated/nevira/$threadId'
      path: '/$threadId'
      fullPath: '/nevira/$threadId'
      preLoaderRoute: typeof AuthenticatedNeviraThreadIdRouteImport
      parentRoute: typeof AuthenticatedNeviraRoute
    }
  }
}

interface AuthenticatedNeviraRouteChildren {
  AuthenticatedNeviraThreadIdRoute: typeof AuthenticatedNeviraThreadIdRoute
}

const AuthenticatedNeviraRouteChildren: AuthenticatedNeviraRouteChildren = {
  AuthenticatedNeviraThreadIdRoute: AuthenticatedNeviraThreadIdRoute,
}

const AuthenticatedNeviraRouteWithChildren =
  AuthenticatedNeviraRoute._addFileChildren(AuthenticatedNeviraRouteChildren)

interface AuthenticatedNovaRouteChildren {
  AuthenticatedNovaThreadIdRoute: typeof AuthenticatedNovaThreadIdRoute
}

const AuthenticatedNovaRouteChildren: AuthenticatedNovaRouteChildren = {
  AuthenticatedNovaThreadIdRoute: AuthenticatedNovaThreadIdRoute,
}

const AuthenticatedNovaRouteWithChildren =
  AuthenticatedNovaRoute._addFileChildren(AuthenticatedNovaRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedNeviraRoute: typeof AuthenticatedNeviraRouteWithChildren
  AuthenticatedNovaRoute: typeof AuthenticatedNovaRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNeviraRoute: AuthenticatedNeviraRouteWithChildren,
  AuthenticatedNovaRoute: AuthenticatedNovaRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSpotifyCallbackRoute: ApiSpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
